service: app

provider:
    name: aws
    region: us-east-1
    runtime: provided

plugins:
    - ./vendor/bref/bref

functions:
    api:
        handler: public/index.php
        description: ''
        timeout: 28
        layers:
            - ${bref:layer.php-73-fpm}
        events:
            -   http: 'OPTIONS /'
